repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: validate-example-readmes
        name: Validate Example README Commands
        entry: bash scripts/pre-commit-hook
        language: system
        files: ^examples/.*/README\.md$
        pass_filenames: false
        always_run: true